server:
  port: 8080

spring:
  application:
    name: spring-certification-lab

app:
  environment: default
  message: Default configuration loaded
  owner: Donato

logging:
  level:
    com.donatodev.springlab: INFO