server:
  port: 8081

spring:
  application:
    name: spring-certification-lab

app:
  message: Configuration loaded from application.yml
  owner: Donato

logging:
  level:
    com.donatodev.springlab: INFO